version: "3.9"

services:
  backend:
    build: ./backend
    container_name: password-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=
      - PORT=3000

  frontend:
    build: ./frontend
    container_name: password-frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
